### ISSUE TITLE
crashing when used with orgins mod

### ISSUE THREAD

**Issue by void513** [jeremiahwinsley/flickerfix#1]
it crashes the game when used with Orgins mod.
heres a copy of the crash report   https://www.pastiebin.com/625492ec79b15

think create some kind rendering issue,I have already sent report to developer of orgins mod. 
it be found here
https://github.com/EdwinMindcraft/origins-architectury/issues/145

**Comment by jeremiahwinsley** [comment]
FlickerFix doesn't touch any of the classes mentioned in your crash report. This doesn't look related to me. Does it work correctly without FlickerFix?

**Comment by void513** [comment]
yes after i removed flickerfix it loaded up fine or if i remove orgins mod an leave flickerfix mod loads up fine

**Comment by void513** [comment]
dont know if it help but im using flickerfix-2.0.0.jar on minecraft 1.18.2

**Comment by void513** [comment]
dont know if this will help either but heres the debug log 
https://www.pastiebin.com/6254de0d2b9e4

**Comment by jeremiahwinsley** [comment]
Yes, that's helpful. It looks like Origins packages the Apoli mod, which also includes a fix for night vision flickering. You can just remove FlickerFix.

I consider this "working as intended" because that's all this mod does, and there's no point having two mods that fix this issue.
