### ISSUE TITLE
Infinite effect will be disabled

### ISSUE THREAD

**Issue by Dr-WeiAL** [jeremiahwinsley/flickerfix#2]
After changing the time of night vision to infinite, night vision will not take effect
![image](https://github.com/jeremiahwinsley/flickerfix/assets/47446553/3a1b2e1c-632d-4d70-a118-ca3d26f244b0)

Minecraft version: 1.20.1

**Comment by jeremiahwinsley** [comment]
Thanks for the report, fixed in v4.0.1.
